# permissions for end users to view automations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: automation-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - automations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - automations/status
  verbs:
  - get
